# Generated by Django 4.2.16 on 2024-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='tag',
            field=models.CharField(choices=[('salgado', 'Salgado'), ('doce', 'Doce'), ('bebida', 'Bebida'), ('bala', 'Bala')], default='salgado', max_length=10),
        ),
    ]
